### ISSUE TITLE
可以通过virtual text显示提示吗？

### ISSUE THREAD

**Issue by xuwei152** [luozhiya/fittencode.nvim#22]
目前的提示如下图，不太好区分提示和已经键入的文本
![Clip_2024-04-17_12-37-33](https://github.com/luozhiya/fittencode.nvim/assets/51861161/8472fb17-2436-4c52-b5e6-080b4a7be299)

有没有可能像codeium 一样用virtual text显示提示

![Clip_2024-04-17_13-40-44](https://github.com/luozhiya/fittencode.nvim/assets/51861161/8673361c-d82c-4d95-933f-3c4a684bc86a)

**Comment by luozhiya** [comment]
@xuwei152 

> 不太好区分提示和已经键入的文本

之所以无法区分，是因为提示的高亮和上下文的高亮近似引起的。
目前的默认高亮颜色和 `fittencode` 在 `vscode/vim` 中是一致，您可以重新定义一下高亮，比如

```lua
vim.api.nvim_set_hl(0, 'FittenSuggestion', {
  fg = '#a1a1a1',
})
```

> 用virtual text显示提示

实现方面的话已经是通过 virtual text (extmark) 实现的了。

**Comment by xuwei152** [comment]
可以了谢谢
