### ISSUE TITLE
source 模式 使用cmp补全 有成功的先例吗？

### ISSUE THREAD

**Issue by cxwx** [luozhiya/fittencode.nvim#23]
inline 使用没有问题，但是与 codeium.vim 是互相冲突的，二者都用 virtual text 模式，
故改用 cmp 插件，但似乎没法使用cmp触发

**Comment by luozhiya** [comment]
@cxwx 

您是怎样配置 `source` 和 `nvim-cmp` 的，可以复现吗

**Comment by cxwx** [comment]
1：是我搞错了，fitten code 已经成功补全，只是显示的为 “text”，
<img width="449" alt="截屏2024-04-19 22 35 47" src="https://github.com/luozhiya/fittencode.nvim/assets/6235641/d6bad3ff-5da0-409e-a433-efa6bb651e00">
如果能使用 [lspkind](https://github.com/onsails/lspkind.nvim) 就更好了

2: cmp 如何才能支持多行补全？

**Comment by cxwx** [comment]
在`nvim-cmp`下面`entry.lua`下面
```
    local cmp_opts = self:get_completion_item().cmp or {}

    local vim_item = {
      word = word,
      abbr = abbr,
      kind = cmp_opts.kind_text or types.lsp.CompletionItemKind[self:get_kind()] or types.lsp.CompletionItemKind[1],
      kind_hl_group = cmp_opts.kind_hl_group,
      menu = menu,
      dup = self:get_completion_item().dup or 1,
    }
```
要想改变返回的 kind_text 似乎是要加上 cmp.kind_text 选项。

**Comment by luozhiya** [comment]
@cxwx 

> cmp 如何才能支持多行补全？

现在其实是支持多行的了，但是在 cmp 的提示列表中会把换行符用 `<\n>` 折叠起来成一行。
![image](https://github.com/luozhiya/fittencode.nvim/assets/90168447/454151dd-4376-4826-94e3-e7ca67206805)

> 只是显示的为 “text”
> 能使用 [lspkind](https://github.com/onsails/lspkind.nvim) 就更好了

刚更新了，添加了 `FittenCode` 的类型提示；
`lspkind` 也是支持的了，只需在 `symbol_map` 中添加 `FittenCode`  与相应图标的映射即可。

**Comment by cxwx** [comment]
感谢回复：
1，似乎多行补全和所用的语言还有点关系，对python可以实现多行补全，这应是cmp本身的问题，
2，我的理解 FittenCode 的返回cmp的table 里头必须加上定义 return {...,  cmp= {kind_text = "自定义新的类型"}}， 否则将识别为通用的text，simbol_map 也只能匹配为text的图标
比如 codeium 返回值中
```
	return {
		type = 1,
		documentation = {
			kind = "markdown",
			value = table.concat({
				"```" .. vim.api.nvim_buf_get_option(0, "filetype"),
				label,
				"```",
			}, "\n"),
		},
		label = label,
		insertText = label,
		textEdit = {
			newText = label,
			insert = range,
			replace = range,
		},
		cmp = {  -- this line set type Codeium
			kind_text = "Codeium",
			kind_hl_group = "CmpItemKindCodeium",
		},
		codeium_completion_id = comp.completion.completionId,
	}

```

**Comment by luozhiya** [comment]
@cxwx 

自定义类型就是 `FittenCode`，在之前的 commit 里添加了，您更新一下的 commit 应该就可以了

https://github.com/luozhiya/fittencode.nvim/pull/25/files#diff-243370d50a9fcd8f6312d57425402b70e4eccb3569aa0a761224990255dd6444R448

**Comment by cxwx** [comment]
感谢

**Comment by luozhiya** [comment]
@cxwx 您客气了
