### ISSUE TITLE
value too large

### ISSUE THREAD

**Issue by ErrEoE** [luozhiya/fittencode.nvim#29]
<img width="781" alt="1714473083534" src="https://github.com/luozhiya/fittencode.nvim/assets/14369333/7636db63-05c6-4d44-bbfe-4a9ec73fb698">
Using it in go project, it occur error after a few time! I use inline mode.

**Comment by luozhiya** [comment]
Hi @ErrEoE 

Can it be reproduced? Set the log level to debug and take a look at the logs.

```lua
log = {
  level = vim.log.levels.DEBUG,
},
```
