### ISSUE TITLE
c++ 补全换行问题。

### ISSUE THREAD

**Issue by cxwx** [luozhiya/fittencode.nvim#71]
\n
无法正确使用，

配置使用 nvim-cmp

<img width="472" alt="截屏2024-05-24 17 31 24" src="https://github.com/luozhiya/fittencode.nvim/assets/6235641/3b069629-a59a-43f0-9107-f4db130851ff">

<img width="472" alt="截屏2024-05-24 17 32 30" src="https://github.com/luozhiya/fittencode.nvim/assets/6235641/695ab98d-561a-4481-892d-3b45a83a9ab5">

**Comment by luozhiya** [comment]
@cxwx 

多行补全需要设置一下cmp
```
mapping = { ['<cr>'] = cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Insert, select = false }), }
```

**Comment by cxwx** [comment]
应该是我的 tab 配置出现问题，
当仅有1个fittencode补全的时候会自动填充，
```lua
          ["<Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
              cmp.select_next_item()
            elseif luasnip.expand_or_jumpable() then
              luasnip.expand_or_jump()
            else
              fallback()
            end
          end, { "i", "s" }),

```

**Comment by luozhiya** [comment]
@cxwx 

您找到解决方法了吗

**Comment by cxwx** [comment]
我通石开Codeium Tabnine 和  fittencode，补全不止一行，就不会出问题😆😆😆

**Comment by luozhiya** [comment]
@cxwx

这个问题挺奇怪的，按 `cmp` 设计，多行要正确展开要调用 `conform`，用 Tab (select_next_item) 的话，只能插入第一行。
在只有一个补全的情况下，也需要用 `conform` 来展开。

在 #102 中改进了一下 cmp，支持 [多行 ghost_text](https://github.com/hrsh7th/nvim-cmp/pull/1886) 
另外去掉了首行是空行的补全，因为 cmp 会剪裁掉空行，使得结果不一致。

**Comment by cxwx** [comment]
我感觉cmp只是个过度方案，插件太混乱，迟早要被替代，只是目前没有

**Comment by cxwx** [comment]
看似blink.cmp 更加稳定
