### ISSUE TITLE
Feature request: Is it possible to add a command to close the chat?

### ISSUE THREAD

**Issue by xuwei152** [luozhiya/fittencode.nvim#74]
After chating with the fittencode, I have to jump to the chat panel to close it. Is it possible to add a command to close the chat panel or change the command “Fitten show_chat”  to “Fitten toggle_chat"?
![Clip_2024-05-27_16-20-49](https://github.com/luozhiya/fittencode.nvim/assets/51861161/79f960de-b80c-4814-af50-970aa5be3a0b)

**Comment by luozhiya** [comment]
@xuwei152 

`toggle_chat`  is already implemented in this https://github.com/luozhiya/fittencode.nvim/commit/2fc5ee0fed571b9e0b4c7d0b59119eca9bf07571 commit.

Please update to latest commit.
