### ISSUE TITLE
请问一下，是不是没有手动切换插件开关的Api呀

### ISSUE THREAD

**Issue by ziboh** [luozhiya/fittencode.nvim#80]

**Comment by luozhiya** [comment]
您的意思是 VSCode版本的FittenCode中的 `Disable global completions` 这个开关吗？

![image](https://github.com/luozhiya/fittencode.nvim/assets/90168447/ad6cb01e-38e4-4e47-beff-26e63abc35c6)

**Comment by ziboh** [comment]
是的，我现在在学习rust,我希望在写例子的时候关闭fittencode的提示。我发现只有退出fittencode登录的api，如果使用logout后，又需要重新登录了。

**Comment by luozhiya** [comment]
@ziboh 

请更新一下，#82 新添加了 `enable_completions `/`disable_completions`
