### ISSUE TITLE
无法关闭行内样式的补全

### ISSUE THREAD

**Issue by Rav4n-T** [luozhiya/fittencode.nvim#86]
无法关闭 inline completion
无论是按照文档设置
![image](https://github.com/luozhiya/fittencode.nvim/assets/155917703/3b68c203-e949-4917-9381-167f7decc385)
还是将inline_completion设置为false,都无法关闭行内补全
![image](https://github.com/luozhiya/fittencode.nvim/assets/155917703/75d9a2bc-2cbb-42f9-b3ac-378952ad0fa1)

我使用cmp进行补全工作，希望cmp能完全接管 fitencode 的补全，触发方式由 cmp 的配置决定，而不是一直触发行内补全

**Comment by luozhiya** [comment]
@Rav4n-T 

这个看上去像是 `cmp` 显示的

**Comment by Rav4n-T** [comment]
我同时使用了另一个ai插件，codeium.nvim，在完全删除字符后，codeium并没有触发补全，只有fittencode.nvim 触发了

**Comment by Rav4n-T** [comment]
> @Rav4n-T
> 
> 这个看上去像是 `cmp` 显示的，和 `inline` 没有关系， `inline` 的配置是和 `source` 独立的，除了 `disable_specific_inline_completion` 选项。
> 
> > 删除完所有字符时，不应该触发补全
> 
> `cmp` 回调里只有触发的字符，没有提供相关的事件源信息，并不能判断当前是删除还是插入。


我同时使用了另一个ai插件，codeium.nvim，在完全删除字符后，codeium并没有触发补全，只有fittencode.nvim 触发了

**Comment by luozhiya** [comment]
@Rav4n-T 

`fittencode.nvim` 默认设置的 `trigger_characters` 范围比较大，是允许在换行和空行的情况下提供补全的

**Comment by Rav4n-T** [comment]
@luozhiya 
是否有方法可以通过配置修改呢？

**Comment by Rav4n-T** [comment]
@luozhiya 
我找到问题所在了，是因为trigger_characters表中的空格触发的补全
![image](https://github.com/luozhiya/fittencode.nvim/assets/155917703/ed72d512-18ec-4e51-91e1-ef03291a305e)
我删除了32号字符（即ascii表中的空格）和你下面定义的空格字符，就正常了

**Comment by Rav4n-T** [comment]
或许在配置里可以加一个字段用于用户自定义trigger_characters

**Comment by luozhiya** [comment]
@Rav4n-T 

> 或许在配置里可以加一个字段用于用户自定义trigger_characters

如果您感兴趣的话，欢迎提交PR。

另外，`cmp` 这块后续计划重构一下，提供更好的兼容性。

**Comment by R0boter** [comment]
> @Rav4n-T
> 
> > 或许在配置里可以加一个字段用于用户自定义trigger_characters
> 
> 如果您感兴趣的话，欢迎提交PR。
> 
> 另外，`cmp` 这块后续计划重构一下，提供更好的兼容性。

我提交了一个PR,很抱歉我对lua不是很熟悉，如果代码有什么请告诉我，谢谢您的帮组
