### ISSUE TITLE
是否存在能够取消补全的lua接口，或者类似的方式能够取消补全

### ISSUE THREAD

**Issue by Kaiser-Yang** [luozhiya/fittencode.nvim#89]
由于个人习惯原因，我使用回车键作为补全的接受按键，因此当我需要输入回车而当前存在补全的时候，我输入回车会接受所有的补全，而我想知道能否有取消本次补全的接口（例如`copilot`中的`copilot#Dismiss()`），这样我可以绑定`<C-C>`来取消本次补全进而可以通过`<CR>`来换行。

**Comment by luozhiya** [comment]
@Kaiser-Yang 

目前没有直接的API，绕一点的话可以通过 `require('fittencode.engines.inline').reset()` 实现类似的功能

**Comment by Kaiser-Yang** [comment]
OK，谢谢回复，我试试

**Comment by Kaiser-Yang** [comment]
但是这个有问题，reset之后他会马上加载出来。

**Comment by Kaiser-Yang** [comment]
@luozhiya 
我看主页写了可以集成到coc里面， 如果能够集成到coc里面的话，就可以通过`coc`的接口来取消：
![image](https://github.com/luozhiya/fittencode.nvim/assets/58209855/00764f60-2e18-4724-8e43-533dc3fce3c2)

但是`source mode`部分只给了`cmp`的配置，请问我使用`coc`的话应该如何配置？
![image](https://github.com/luozhiya/fittencode.nvim/assets/58209855/e56abb3b-fb1f-4cbf-9263-0495cd29448b)

**Comment by luozhiya** [comment]
@Kaiser-Yang 

`coc` 处于 WIP 状态，目前还没有提供，您可以看下 #55 有列出计划事项

**Comment by Kaiser-Yang** [comment]
好的。

**Comment by Kaiser-Yang** [comment]
我找一个巧妙的方法可以实现我的需求，当存在`fitencode`补全的时候，通过`<C-c>`清楚当前补全并关闭所有补全，而在需要的时候通过`<C-Space>`即可再次触发补全：
```lua
vim.cmd[[
inoremap <silent><expr> <C-c>
      \ coc#pum#visible() ? coc#pum#cancel() :
      \ luaeval('require("fittencode").has_suggestions()') ? '<cmd>lua require("fittencode.engines.inline").reset()<cr><cmd>Fitten disable_completions<cr>' : "\<C-c>"
inoremap <silent><expr> <c-space> luaeval('require("fittencode").has_suggestions()') ? "\<c-space>" : '<cmd>Fitten enable_completions<cr>'
]]
```

**Comment by luozhiya** [comment]
@Kaiser-Yang 

#94 新加了API `dismiss_suggestions`

**Comment by Kaiser-Yang** [comment]
感谢，辛苦了。
