### ISSUE TITLE
只能部分补全，不能一次性补全

### ISSUE THREAD

**Issue by Kaiser-Yang** [luozhiya/fittencode.nvim#95]
我查看主页的演示发现是可以一次性补全一整个函数或者功能的，但是在我使用的时候，我发现我只能一次补全一行或者简短的几行，必须要先接受这几行补全后才会继续补全，是需要我进行其他的设置吗？
![image](https://github.com/luozhiya/fittencode.nvim/assets/58209855/071396b7-a2d2-48ac-a201-f22a002ecc49)

**Comment by luozhiya** [comment]
@Kaiser-Yang 

不需要额外的设置，每次补全的结果会有差异。

**Comment by Kaiser-Yang** [comment]
我测试快速排序等简单的函数，发现都只能补全部分行，而不能一次补全整个函数，但是copilot却可以，也就是说这是fitten code本身的问题？

**Comment by luozhiya** [comment]
应该和 fitten code 没有关系，vscode 里可以补全整个 KMP 算法

**Comment by luozhiya** [comment]
- 现在用的api和README里演示用的是同一个
- 实现的话，虽然改了几版，但应该对inline的补全结果影响比较小

感觉是因为补全结果有随机性，刚测了一下，Neovim里又可以补全整个KMP算法了。

**Comment by Kaiser-Yang** [comment]
> > 那这个是这个插件的实现问题还是官方开放的api的问题，如果我能需要我帮忙的我会尽力帮忙。
> 
> 好的，谢谢
> 
> * 现在用的api和README里演示用的是同一个
> * 实现的话，虽然迭代了几版，但应该对inline的补全结果影响比较小
> 
> 感觉是因为补全结果有随机性，刚测了一下，Neovim里又可以补全整个KMP算法了。

我刚刚也测试了一下，好像确实可以了
